@host=http://localhost:5044

POST {{host}}/auth/register
Content-Type: application/json

{
    
    "password": "abc123456",
    "firstName": "Ahsan",
    "email": "ahsanfarooq860@gmail.com",
    "lastName": "Farooq"
}