@host=http://localhost:5044
@token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAiLCJlbWFpbCI6ImFoc2FuZmFyb29xODYwQGdtYWlsLmNvbSIsImdpdmVuX25hbWUiOiJBaHNhbiIsImZhbWlseV9uYW1lIjoiRmFyb29xIiwianRpIjoiMWE2ODgzNTctOGEyNy00ODhjLTkwMmQtMmUyZTMxMjMwOGMwIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3MzU4Nzg5NDMsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTA0NCIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAwIn0.tZKWNXlQFBP3AiqA7tlQdY3Biegdq_pqnaseQcEj764"

GET {{host}}/Dinner/GetDinner
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAiLCJlbWFpbCI6ImFoc2FuZmFyb29xODYwQGdtYWlsLmNvbSIsImdpdmVuX25hbWUiOiJBaHNhbiIsImZhbWlseV9uYW1lIjoiRmFyb29xIiwianRpIjoiMmRlMDVmZDUtY2MwNC00MDc5LTg5NDgtOGU2YmMzZGIzZmMxIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3MzU4Nzk1MTUsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTA0NCIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAwIn0.ym7DiR7pSuE_dpv_u-DvOjzC14C5oonKtSfkdszglPk